<?php 
//front

$url = 'https://web.njit.edu/~hy276/beta/back/selectExam.php';
//$url = 'https://web.njit.edu/~hy276/beta/mid/selectExam.php';

//var_dump($_POST);

if (isset($_POST['exam_name'])) {
  $exam_name = $_POST['exam_name'];
  if ($exam_name === NULL) {
    die("POST info is NULL");
  } 
}
$send = urlencode("exam_name=$exam_name");
//var_dump($send);
/*
$post = array( 
  "exam_name" => $exam_name
); 
*/
//var_dump($post);
//$send = json_encode($post, true);

$opts = array(
  //CURLOPT_HTTPHEADER => array("Content-Type: application/json", "Accept: application/json"),
  CURLOPT_URL => $url,
  CURLOPT_RETURNTRANSFER => 1,
  CURLOPT_FOLLOWLOCATION => 1,
  CURLOPT_POST => 1,
  CULROPT_POSTFIELDS => $send
);

$ch = curl_init();

curl_setopt_array($ch, $opts);

$result = curl_exec($ch); //curl request doesn't send right

if ($result === false) {
  die("could not establish curl");
}

if (curl_errno($ch)) {
  die("error" . curl_error($ch));
}

curl_close($ch);

echo $result;

/* code that works 
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://web.njit.edu//~hy276/beta/back/selectExam.php');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"exam_name\":\"Exam1\"}");
curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);
echo $result;*/

